apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: externalnodepromrules
  namespace: monitoring
spec:
  groups:
  - name: blackbox-exporter.rules
    rules:
    - alert: EndpointDown
      expr: probe_success == 0
      for: 10s
      labels:
        severity: "严重"
      annotations:
        summary: "Endpoint {{ $labels.instance }} down"
