apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox
  namespace: monitoring-external
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: blackbox
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blackbox
    spec:
      containers:
      - image: bitnami/blackbox-exporter
        name: blackbox
        args:
        - --log.level=info  # 日志级别，可以把级别调到 error
        ports:
        - containerPort: 9115
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox
  namespace: monitoring-external
  labels:
    app: blackbox-exporter
spec:
  selector:
    app: blackbox
  ports:
  - name: http-9115    
    port: 9115
    targetPort: 9115
