apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
      "smtp_smarthost": "smtp.exmail.qq.com:465"
      "smtp_from": "it-monitor@kuaiche100.cn"
      "smtp_auth_username": "it-monitor@kuaiche100.cn"
      "smtp_auth_password": "Dida#1..2017"
      "smtp_require_tls": false
    "inhibit_rules":
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "critical"
      "target_match_re":
        "severity": "warning|info"
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "warning"
      "target_match_re":
        "severity": "info"
    "receivers":
    - "name": "Default"
      "email_configs":
      - "to": "dujc@kuaiche100.cn"
        "send_resolved": true
    - "name": "Watchdog"
      "email_configs":
      - "to": "dujc@kuaiche100.cn"
        "send_resolved": true
    - "name": "Critical"
      "email_configs":
      - "to": "dujc@kuaiche100.cn"
        "send_resolved": true
    "route":
      "group_by":
      - "namespace"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "Default"
      "repeat_interval": "12h"
      "routes":
      - "match":
          "alertname": "Watchdog"
        "receiver": "Watchdog"
      - "match":
          "severity": "critical"
        "receiver": "Critical"
type: Opaque
