apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: externalnodepromrules
  namespace: monitoring
spec:
  groups:
    - name: 主机状态-监控告警
      rules:
        - alert: 主机状态
          annotations:
            description: '{{$labels.instance}}:服务器延时超过5分钟'
            summary: '{{$labels.instance}}:服务器宕机'
          expr: 'up{job=~"^.*node-exporter"} == 0'
          for: 1m
          labels:
            status: 非常严重
        - alert: CPU使用情况
          annotations:
            description: '{{$labels.mountpoint }} CPU使用大于60%(目前使用:{{$value}}%)'
            summary: '{{$labels.mountpoint}} CPU使用率过高！'
          expr: >-
            100-(avg(irate(node_cpu_seconds_total{mode="idle"}[5m]))
            by(instance)* 100) > 60
          for: 1m
          labels:
            status: 一般告警
        - alert: 内存使用
          annotations:
            description: '{{$labels.mountpoint }} 内存使用大于80%(目前使用:{{$value}}%)'
            summary: '{{$labels.mountpoint}} 内存使用率过高！'
          expr: >-
            (1-(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))* 100 > 80
          for: 1m
          labels:
            status: 严重告警
        - alert: IO性能
          annotations:
            description: '{{$labels.mountpoint }} 流入磁盘IO大于60%(目前使用:{{$value}})'
            summary: '{{$labels.mountpoint}} 流入磁盘IO使用率过高！'
          expr: >-
            100-(avg(irate(node_disk_io_time_seconds_total[1m])) by(instance)*
            100) < 60
          for: 1m
          labels:
            status: 严重告警
        - alert: 网络
          annotations:
            description: '{{$labels.mountpoint }}流入网络带宽持续2分钟高于100M. RX带宽使用率{{$value}}'
            summary: '{{$labels.mountpoint}} 流入网络带宽过高！'
          expr: >-
            ((sum(rate
            (node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m]))
            by (instance)) / 100) > 102400
          for: 1m
          labels:
            status: 严重告警
        - alert: 网络
          annotations:
            description: '{{$labels.mountpoint }}流出网络带宽持续2分钟高于100M. RX带宽使用率{{$value}}'
            summary: '{{$labels.mountpoint}} 流出网络带宽过高！'
          expr: >-
            ((sum(rate
            (node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m]))
            by (instance)) / 100) > 102400
          for: 1m
          labels:
            status: 严重告警
        - alert: TCP会话
          annotations:
            description: '{{$labels.mountpoint }} TCP_ESTABLISHED大于1000%(目前使用:{{$value}}%)'
            summary: '{{$labels.mountpoint}} TCP_ESTABLISHED过高！'
          expr: node_netstat_Tcp_CurrEstab > 1000
          for: 1m
          labels:
            status: 严重告警
        - alert: 系统磁盘容量
          annotations:
            description: '{{$labels.mountpoint }} 磁盘分区使用大于80%(目前使用:{{$value}}%)'
            summary: '{{$labels.mountpoint}} 磁盘分区使用率过高！'
          expr: >-
            100-(node_filesystem_free_bytes{device="/dev/vda1",fstype=~"ext4|xfs"}/node_filesystem_size_bytes
            {device="/dev/vda1",fstype=~"ext4|xfs"}*100) > 80
          for: 1m
          labels:
            status: 严重告警
        - alert: 数据磁盘容量
          annotations:
            description: '{{$labels.mountpoint }} 磁盘分区使用大于80%(目前使用:{{$value}}%)'
            summary: '{{$labels.mountpoint}} 磁盘分区使用率过高！'
          expr: >-
            100-(node_filesystem_free_bytes{device="/dev/vdb1",fstype=~"ext4|xfs"}/node_filesystem_size_bytes
            {device="/dev/vdb1",fstype=~"ext4|xfs"}*100) > 80
          for: 1m
          labels:
            status: 严重告警
