apiVersion: v1
kind: Service
metadata:
  name: external-node-exporter
  namespace: monitoring-external
  labels:
    app: external-node-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-9100
    port: 9100
    protocol: TCP
    targetPort: http-9100
  sessionAffinity: None
  externalIPs:
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-node-exporter
  namespace: monitoring-external
  labels:
    app: external-node-exporter
subsets:
- addresses:
  - ip: 10.64.4.146
    nodeName: prod-dockerjack
  - ip: 10.64.4.155
    nodeName: prod-dockerrose
  - ip: 10.64.4.142
    nodeName: prod-dida-tomcat2
  - ip: 116.62.41.153
    nodeName: prod-yaojet-nginx
  - ip: 116.62.41.156
    nodeName: prod-yaojet-dida
  - ip: 121.196.197.231
    nodeName: prod-dida-tomcat1
  - ip: 121.43.184.235
    nodeName: prod-dockermother
  - ip: 120.27.210.244
    nodeName: prod-nginx
  - ip: 121.196.207.81
    nodeName: pre-pre01
  - ip: 121.196.213.109
    nodeName: intservice-pubservice
  - ip: 10.64.4.156
    nodeName: jumpserver
  - ip: 10.64.4.207
    nodeName: kuaicheweb
  ports:
  - name: http-9100
    port: 9100
    protocol: TCP
