apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerjack-mongo-exporter
  namespace: monitoring-external
  labels:
    k8s-app: dockerjack-mongo-exporter
spec:
  selector:
    matchLabels:
      k8s-app: dockerjack-mongo-exporter
  template:
    metadata:
      labels:
        k8s-app: dockerjack-mongo-exporter
    spec:
      containers:
      - name: dockerjack-mongo-exporter
        image: bitnami/mongodb-exporter
        args: ["--web.listen-address=:9104", "--mongodb.uri", "mongodb://administrator:WeLoveShengxi666@10.64.4.146:27017"]
        ports:
        - containerPort: 9104
          name: http-9104

---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: dockerjack-mongo-exporter
    mongo: exporter
  name: dockerjack-mongo-exporter
  namespace: monitoring-external
spec:
  type: ClusterIP
  ports:
  - name: http-9104
    port: 9104
    targetPort: http-9104
  selector:
    k8s-app: dockerjack-mongo-exporter
